TOKEN="5257611391:AAG60osMCnhDnkhf12v5KpVcFrdd9mhkf0k"
URL_OMIRBAIAN="https://www.instagram.com/"
URL_JETISTIKTER="https://facebook.com/"
URL_OQYSHYJESTISTIGI="https://www.pinterest.ru/"
URL_ZERTTEYLERI="https://www.figma.com/"
URL_ASHYQSABAQTAR="https://www.canva.com/"